name: Ruby

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, truffleruby, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        sudo apt-get update
        sudo apt-get install libncurses5-dev libncursesw5-dev libxml2-dev libxslt-dev sqlite3 mysql-server postgresql postgresql-contrib
        bundle install
        bundle exec rake test rails/actionpack/test/journey
